-- Policy tables for the isolated authentication adapter proof. Better Auth's
-- versioned PostgreSQL schema is generated by getMigrations in the harness.
CREATE TABLE users(id text PRIMARY KEY,email text UNIQUE NOT NULL,display_name text NOT NULL);
CREATE TABLE account_security(user_id text PRIMARY KEY REFERENCES users(id),status text NOT NULL,auth_version integer NOT NULL DEFAULT 1,recovery_required integer NOT NULL DEFAULT 0);
CREATE TABLE instance_memberships(user_id text PRIMARY KEY REFERENCES users(id),role text NOT NULL CHECK(role IN ('owner','admin','member','guest')));
CREATE UNIQUE INDEX one_owner ON instance_memberships(role) WHERE role = 'owner';
CREATE TABLE installation(id text PRIMARY KEY,state text NOT NULL DEFAULT 'unclaimed',setup_user_id text,owner_id text,version integer NOT NULL DEFAULT 1);
INSERT INTO installation(id) VALUES ('instance');
CREATE TABLE request_limits(key text,bucket bigint,count integer NOT NULL,updated_at timestamptz,PRIMARY KEY(key,bucket));
CREATE TABLE security_outbox(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,kind text NOT NULL,payload jsonb NOT NULL);
CREATE TABLE security_audit(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,action text NOT NULL,target_id text);
