const labels: Record<string, string> = {
  "updates.connection_saved": "Update connection saved",
  "updates.disconnected": "Update connection disconnected",
  "updates.requested": "Software update requested",
  "updates.rollback_requested": "Compatible version restore requested",
  "updates.policy_changed": "Automatic update preference changed",
  "updates.preparation_cancelled": "Stalled update preparation cleared",
  "updates.deployment_retried": "Stopped deployment retried",
  "updates.verified": "Updated deployment verified",
  "auth.sign-in.local":"Username sign-in",
  "auth.setup.local":"Local account created",
  "auth.recover.local":"Account recovery started",
  "account.recovery_key_replaced":"Account recovery key replaced",
  "local_invitation.created":"Private invitation created",
  "local_invitation.revoked":"Private invitation revoked",
  "auth.sign-in.email": "Password sign-in",
  "auth.two-factor.verify-totp": "Authenticator verified",
  "auth.two-factor.enable": "Authenticator enrollment started",
  "auth.two-factor.disable": "Authenticator removed",
  "auth.two-factor.verify-backup-code": "Recovery code verified",
  "auth.passkey.verify-authentication": "Signed in with a passkey",
  "auth.passkey.verify-registration": "Passkey added",
  "auth.operator-recovery": "Emergency recovery confirmed",
  "account.factor_recovered": "Recovery completed",
  "account.recovery_code_used": "Recovery started with a saved code",
  "account.emergency_recovery_started": "Emergency owner recovery started",
  "account.emergency_recovery_issued": "Operator issued an owner recovery link",
  "account.password_reset": "Password reset",
  "account.password_changed": "Password changed and access revoked",
  "account.password_added": "Password added and access revoked",
  "account.secured": "Account secured and apps disconnected",
  "account.email_changed": "Email address changed",
  "session.all_revoked": "Signed out all devices",
  "session.revoked": "Session signed out",
  "oauth.permissions_confirmed": "App permissions confirmed",
  "oauth.consent_granted": "App connected",
  "oauth.disconnected": "App disconnected",
  "admin.content_transferred": "Content ownership transferred",
  "board.ownership_transferred": "Board ownership transferred",
  "workbook.ownership_transferred": "Workbook ownership transferred",
  "admin.approve": "Account approved",
  "admin.suspend": "Account suspended",
  "admin.restore": "Account restored",
  "installation.settings_changed": "Installation settings changed",
};
export function securityEventLabel(action: string) {
  const value = labels[action] ?? action.replaceAll(/[._/-]/g, " ");
  return value.charAt(0).toUpperCase() + value.slice(1);
}
